#!/usr/bin/env python3
"""Convert the eSheep animations.xml behavior graph into a C data table.

Source: Adrianotiger/desktopPet's Pets/esheep64/animations.xml (see NOTICE.md).
This is a one-time offline tool -- its output (src/animations_data.c/.h) is
committed and compiled directly into the engine, so the app never parses XML
at runtime.
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

NS = {"e": "https://esheep.petrucci.ch/"}


def tag(el, name, default=None, cast=str):
    child = el.find(f"e:{name}", NS)
    if child is None or child.text is None:
        return default
    return cast(child.text.strip())


def parse_transitions(parent, tagname="next"):
    out = []
    if parent is None:
        return out
    for n in parent.findall(f"e:{tagname}", NS):
        out.append(
            {
                "probability": int(n.get("probability", "100")),
                "only": n.get("only"),
                "target": int(n.text.strip()),
            }
        )
    return out


def parse_childs(root):
    """Parse child animation records from the <childs> section."""
    out = []
    childs_el = root.find("e:childs", NS)
    if childs_el is None:
        return out
    for child in childs_el.findall("e:child", NS):
        anim_id = int(child.get("animationid"))
        x = tag(child, "x", "0", str)
        y = tag(child, "y", "0", str)
        next_id = tag(child, "next", "0", int)
        out.append({
            "animation_id": anim_id,
            "x": x,
            "y": y,
            "next": next_id,
        })
    return out


def parse_pose(el):
    return {
        "x": tag(el, "x", "0", str),
        "y": tag(el, "y", "0", str),
        "interval": tag(el, "interval", "100", int),
        "offsety": tag(el, "offsety", "0", str),
        "opacity": tag(el, "opacity", "1.0", float),
    }


def c_str(s):
    if s is None:
        return "NULL"
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def main():
    if len(sys.argv) > 1 and sys.argv[1] in ("-h", "--help"):
        print(__doc__.strip())
        print()
        print("usage: gen_animations.py [INPUT_XML] [OUTPUT_DIR]")
        print()
        print("  INPUT_XML  path to animations.xml (default: tools/esheep_animations.xml)")
        print("  OUTPUT_DIR directory for animations_data.c/.h (default: src)")
        return

    src = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("tools/esheep_animations.xml")
    out_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("src")
    out_dir.mkdir(parents=True, exist_ok=True)

    root = ET.fromstring(src.read_text())

    header = root.find("e:header", NS)
    tilesx = tag(header, "tilesx", "16", int)
    tilesy = tag(header, "tilesy", "11", int)

    spawns = []
    for sp in root.findall("e:spawns/e:spawn", NS):
        spawns.append(
            {
                "id": int(sp.get("id")),
                "probability": int(sp.get("probability", "100")),
                "x": tag(sp, "x", "0", str),
                "y": tag(sp, "y", "0", str),
                "next": parse_transitions(sp),
            }
        )

    animations = []
    for an in root.findall("e:animations/e:animation", NS):
        seq_el = an.find("e:sequence", NS)
        frames = [int(f.text.strip()) for f in seq_el.findall("e:frame", NS)]
        flip = seq_el.find("e:action", NS) is not None and seq_el.find("e:action", NS).text.strip() == "flip"

        animations.append(
            {
                "id": int(an.get("id")),
                "name": tag(an, "name", "", str),
                "start": parse_pose(an.find("e:start", NS)),
                "end": parse_pose(an.find("e:end", NS)),
                "repeat": seq_el.get("repeat", "0"),
                "repeat_from": seq_el.get("repeatfrom", "0"),
                "frames": frames,
                "flip": flip,
                "sequence_next": parse_transitions(seq_el),
                "border_next": parse_transitions(an.find("e:border", NS)),
                "gravity_next": parse_transitions(an.find("e:gravity", NS)),
            }
        )

    childs = parse_childs(root)

    write_header(out_dir / "animations_data.h")
    write_source(out_dir / "animations_data.c", tilesx, tilesy, spawns, animations, childs)
    print(f"wrote {len(animations)} animations, {len(spawns)} spawn points, {len(childs)} child records -> {out_dir}")


def write_header(path):
    path.write_text(
        """/* Generated by tools/gen_animations.py from esheep_animations.xml. Do not edit by hand. */
#ifndef ESHEEP_ANIMATIONS_DATA_H
#define ESHEEP_ANIMATIONS_DATA_H

typedef struct {
    int probability;
    const char *only;   /* NULL, "none", "window", "taskbar", or "vertical" */
    int target;          /* animation id to transition to */
} EsheepTransition;

typedef struct {
    const char *x;       /* pixel delta per frame, or a spawn expression */
    const char *y;
    int interval_ms;
    const char *offsety;
    double opacity;
} EsheepPose;

typedef struct {
    int id;
    int probability;
    const char *x;
    const char *y;
    const EsheepTransition *next;
    int next_count;
} EsheepSpawn;

typedef struct {
    int animation_id;    /* parent animation id */
    const char *x;       /* relative offset expression */
    const char *y;
    int next;            /* child animation id to display */
} EsheepChild;

typedef struct {
    int id;
    const char *name;
    EsheepPose start;
    EsheepPose end;
    const char *repeat;       /* integer literal or expression, e.g. "5+random/10" */
    const char *repeat_from;
    const int *frames;
    int frame_count;
    int flip;
    const EsheepTransition *sequence_next;
    int sequence_next_count;
    const EsheepTransition *border_next;
    int border_next_count;
    const EsheepTransition *gravity_next;
    int gravity_next_count;
} EsheepAnimation;

extern const int esheep_tiles_x;
extern const int esheep_tiles_y;

extern const EsheepSpawn esheep_spawns[];
extern const int esheep_spawn_count;

extern const EsheepAnimation esheep_animations[];
extern const int esheep_animation_count;

extern const EsheepChild esheep_childs[];
extern const int esheep_child_count;

#endif /* ESHEEP_ANIMATIONS_DATA_H */
"""
    )


def emit_transitions(lines, var, transitions):
    lines.append(f"static const EsheepTransition {var}[] = {{")
    for t in transitions:
        lines.append(
            f'    {{ {t["probability"]}, {c_str(t["only"])}, {t["target"]} }},'
        )
    if not transitions:
        lines.append("    { 0, NULL, 0 }, /* unused placeholder, count is 0 */")
    lines.append("};")


def emit_pose(p):
    return (
        f'{{ {c_str(p["x"])}, {c_str(p["y"])}, {p["interval"]}, '
        f'{c_str(p["offsety"])}, {p["opacity"]} }}'
    )


def write_source(path, tilesx, tilesy, spawns, animations, childs):
    lines = []
    lines.append(
        "/* Generated by tools/gen_animations.py from esheep_animations.xml. Do not edit by hand. */"
    )
    lines.append("#include <stddef.h>")
    lines.append('#include "animations_data.h"')
    lines.append("")
    lines.append(f"const int esheep_tiles_x = {tilesx};")
    lines.append(f"const int esheep_tiles_y = {tilesy};")
    lines.append("")

    for sp in spawns:
        emit_transitions(lines, f"spawn{sp['id']}_next", sp["next"])
    lines.append("")
    lines.append("const EsheepSpawn esheep_spawns[] = {")
    for sp in spawns:
        n = len(sp["next"])
        lines.append(
            f'    {{ {sp["id"]}, {sp["probability"]}, {c_str(sp["x"])}, {c_str(sp["y"])}, '
            f'spawn{sp["id"]}_next, {n} }},'
        )
    lines.append("};")
    lines.append(f"const int esheep_spawn_count = {len(spawns)};")
    lines.append("")

    for an in animations:
        aid = an["id"]
        frames_var = f"anim{aid}_frames"
        lines.append(
            f"static const int {frames_var}[] = {{ "
            + ", ".join(str(f) for f in an["frames"])
            + " };"
        )
        emit_transitions(lines, f"anim{aid}_seq_next", an["sequence_next"])
        emit_transitions(lines, f"anim{aid}_border_next", an["border_next"])
        emit_transitions(lines, f"anim{aid}_gravity_next", an["gravity_next"])
        lines.append("")

    lines.append("const EsheepAnimation esheep_animations[] = {")
    for an in animations:
        aid = an["id"]
        lines.append("    {")
        lines.append(f"        {aid}, {c_str(an['name'])},")
        lines.append(f"        {emit_pose(an['start'])},")
        lines.append(f"        {emit_pose(an['end'])},")
        lines.append(f"        {c_str(an['repeat'])}, {c_str(an['repeat_from'])},")
        lines.append(f"        anim{aid}_frames, {len(an['frames'])},")
        lines.append(f"        {1 if an['flip'] else 0},")
        lines.append(f"        anim{aid}_seq_next, {len(an['sequence_next'])},")
        lines.append(f"        anim{aid}_border_next, {len(an['border_next'])},")
        lines.append(f"        anim{aid}_gravity_next, {len(an['gravity_next'])},")
        lines.append("    },")
    lines.append("};")
    lines.append(f"const int esheep_animation_count = {len(animations)};")
    lines.append("")

    lines.append("const EsheepChild esheep_childs[] = {")
    for ch in childs:
        lines.append("    {")
        lines.append(f"        {ch['animation_id']}, {c_str(ch['x'])}, {c_str(ch['y'])}, {ch['next']}")
        lines.append("    },")
    if not childs:
        lines.append("    { 0, NULL, NULL, 0 }, /* unused placeholder, count is 0 */")
    lines.append("};")
    lines.append(f"const int esheep_child_count = {len(childs)};")

    path.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
