/* Generated by tools/gen_animations.py from esheep_animations.xml. Do not edit by hand. */
#ifndef ESHEEP_ANIMATIONS_DATA_H
#define ESHEEP_ANIMATIONS_DATA_H

typedef struct {
    int probability;
    const char *only;   /* NULL, "none", "window", "taskbar", or "vertical" */
    int target;          /* animation id to transition to */
} EsheepTransition;

typedef struct {
    const char *x;       /* pixel delta per frame, or a spawn expression */
    const char *y;
    int interval_ms;
    const char *offsety;
    double opacity;
} EsheepPose;

typedef struct {
    int id;
    int probability;
    const char *x;
    const char *y;
    const EsheepTransition *next;
    int next_count;
} EsheepSpawn;

typedef struct {
    int animation_id;    /* parent animation id */
    const char *x;       /* relative offset expression */
    const char *y;
    int next;            /* child animation id to display */
} EsheepChild;

typedef struct {
    int id;
    const char *name;
    EsheepPose start;
    EsheepPose end;
    const char *repeat;       /* integer literal or expression, e.g. "5+random/10" */
    const char *repeat_from;
    const int *frames;
    int frame_count;
    int flip;
    const EsheepTransition *sequence_next;
    int sequence_next_count;
    const EsheepTransition *border_next;
    int border_next_count;
    const EsheepTransition *gravity_next;
    int gravity_next_count;
} EsheepAnimation;

/* Runtime-selected data. Built-in generated data is installed at startup;
 * validated pet packages may replace these pointers before GTK starts. */
extern int esheep_tiles_x;
extern int esheep_tiles_y;

extern const EsheepSpawn *esheep_spawns;
extern int esheep_spawn_count;

extern const EsheepAnimation *esheep_animations;
extern int esheep_animation_count;

extern const EsheepChild *esheep_childs;
extern int esheep_child_count;

extern const int esheep_default_tiles_x;
extern const int esheep_default_tiles_y;
extern const EsheepSpawn esheep_default_spawns[];
extern const int esheep_default_spawn_count;
extern const EsheepAnimation esheep_default_animations[];
extern const int esheep_default_animation_count;
extern const EsheepChild esheep_default_childs[];
extern const int esheep_default_child_count;

/* Restore the generated built-in data after a runtime package is unloaded. */
void esheep_use_default_animation_data(void);

#endif /* ESHEEP_ANIMATIONS_DATA_H */
