/* Generated by tools/gen_animations.py from esheep_animations.xml. Do not edit by hand. */
#ifndef ESHEEP_ANIMATIONS_DATA_H
#define ESHEEP_ANIMATIONS_DATA_H

typedef struct {
    int probability;
    const char *only;   /* NULL, "none", "window", "taskbar", or "vertical" */
    int target;          /* animation id to transition to */
} EsheepTransition;

typedef struct {
    const char *x;       /* pixel delta per frame, or a spawn expression */
    const char *y;
    int interval_ms;
    const char *offsety;
    double opacity;
} EsheepPose;

typedef struct {
    int id;
    int probability;
    const char *x;
    const char *y;
    const EsheepTransition *next;
    int next_count;
} EsheepSpawn;

typedef struct {
    int id;
    const char *name;
    EsheepPose start;
    EsheepPose end;
    const char *repeat;       /* integer literal or expression, e.g. "5+random/10" */
    const char *repeat_from;
    const int *frames;
    int frame_count;
    int flip;
    const EsheepTransition *sequence_next;
    int sequence_next_count;
    const EsheepTransition *border_next;
    int border_next_count;
    const EsheepTransition *gravity_next;
    int gravity_next_count;
} EsheepAnimation;

extern const int esheep_tiles_x;
extern const int esheep_tiles_y;

extern const EsheepSpawn esheep_spawns[];
extern const int esheep_spawn_count;

extern const EsheepAnimation esheep_animations[];
extern const int esheep_animation_count;

#endif /* ESHEEP_ANIMATIONS_DATA_H */
