/* Generated by tools/gen_animations.py from esheep_animations.xml. Do not edit by hand. */
#include <stddef.h>
#include "animations_data.h"

const int esheep_default_tiles_x = 16;
const int esheep_default_tiles_y = 11;

static const EsheepTransition spawn1_next[] = {
    { 100, NULL, 1 },
};
static const EsheepTransition spawn2_next[] = {
    { 100, NULL, 1 },
};
static const EsheepTransition spawn3_next[] = {
    { 100, NULL, 21 },
};
static const EsheepTransition spawn4_next[] = {
    { 100, NULL, 28 },
};

const EsheepSpawn esheep_default_spawns[] = {
    { 1, 20, "screenW+10", "areaH-imageH", spawn1_next, 1 },
    { 2, 80, "random*(screenW-imageW-50)/100+25", "-imageH-20", spawn2_next, 1 },
    { 3, 3, "screenW+10", "areaH/2-(randS*areaH/2)/120-imageH", spawn3_next, 1 },
    { 4, 3, "screenW", "areaH-imageH", spawn4_next, 1 },
};
const int esheep_default_spawn_count = 4;

static const int anim1_frames[] = { 2, 3 };
static const EsheepTransition anim1_seq_next[] = {
    { 2, "window", 11 },
    { 10, "taskbar", 35 },
    { 90, "none", 1 },
    { 6, "none", 15 },
    { 50, "taskbar", 50 },
    { 50, "window", 49 },
};
static const EsheepTransition anim1_border_next[] = {
    { 100, "none", 2 },
    { 2, "vertical", 37 },
    { 20, "window", 43 },
};
static const EsheepTransition anim1_gravity_next[] = {
    { 100, "none", 5 },
};

static const int anim2_frames[] = { 3, 9, 10 };
static const EsheepTransition anim2_seq_next[] = {
    { 100, NULL, 3 },
};
static const EsheepTransition anim2_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim2_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim3_frames[] = { 10, 9, 3 };
static const EsheepTransition anim3_seq_next[] = {
    { 100, "none", 1 },
    { 5, "taskbar", 26 },
};
static const EsheepTransition anim3_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim3_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim4_frames[] = { 42, 43, 43, 42, 44, 44 };
static const EsheepTransition anim4_seq_next[] = {
    { 100, "none", 1 },
};
static const EsheepTransition anim4_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim4_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim5_frames[] = { 133 };
static const EsheepTransition anim5_seq_next[] = {
    { 100, "none", 6 },
};
static const EsheepTransition anim5_border_next[] = {
    { 100, "none", 9 },
};
static const EsheepTransition anim5_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim6_frames[] = { 46, 46, 46 };
static const EsheepTransition anim6_seq_next[] = {
    { 100, "none", 6 },
};
static const EsheepTransition anim6_border_next[] = {
    { 100, "none", 10 },
};
static const EsheepTransition anim6_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim7_frames[] = { 5, 4, 4 };
static const EsheepTransition anim7_seq_next[] = {
    { 40, "none", 7 },
    { 80, "none", 36 },
    { 20, "taskbar", 25 },
};
static const EsheepTransition anim7_border_next[] = {
    { 100, "vertical", 8 },
};
static const EsheepTransition anim7_gravity_next[] = {
    { 100, "none", 5 },
};

static const int anim8_frames[] = { 62, 62, 63, 64, 65, 66, 67, 68, 69, 70, 6 };
static const EsheepTransition anim8_seq_next[] = {
    { 20, NULL, 2 },
    { 5, NULL, 7 },
    { 80, NULL, 1 },
};
static const EsheepTransition anim8_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim8_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim9_frames[] = { 133, 133, 133, 133, 49, 13, 12, 6 };
static const EsheepTransition anim9_seq_next[] = {
    { 100, "none", 1 },
};
static const EsheepTransition anim9_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim9_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim10_frames[] = { 48, 48, 48, 48, 47 };
static const EsheepTransition anim10_seq_next[] = {
    { 100, "none", 1 },
};
static const EsheepTransition anim10_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim10_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim11_frames[] = { 3, 12, 13, 103, 104, 105, 106 };
static const EsheepTransition anim11_seq_next[] = {
    { 100, NULL, 12 },
};
static const EsheepTransition anim11_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim11_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim12_frames[] = { 104, 105, 104, 104, 103, 13, 12 };
static const EsheepTransition anim12_seq_next[] = {
    { 100, NULL, 1 },
};
static const EsheepTransition anim12_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim12_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim13_frames[] = { 3, 96, 96 };
static const EsheepTransition anim13_seq_next[] = {
    { 100, "none", 1 },
};
static const EsheepTransition anim13_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim13_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim14_frames[] = { 50, 51 };
static const EsheepTransition anim14_seq_next[] = {
    { 100, NULL, 1 },
};
static const EsheepTransition anim14_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim14_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim15_frames[] = { 3, 107, 108, 107, 108, 107, 31, 32, 33, 0, 1 };
static const EsheepTransition anim15_seq_next[] = {
    { 100, "none", 16 },
};
static const EsheepTransition anim15_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim15_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim16_frames[] = { 0, 80, 79, 78, 77, 37, 38, 39, 38, 37, 6 };
static const EsheepTransition anim16_seq_next[] = {
    { 100, NULL, 1 },
};
static const EsheepTransition anim16_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim16_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim17_frames[] = { 3, 6, 7, 8, 8, 7, 8, 8 };
static const EsheepTransition anim17_seq_next[] = {
    { 100, "none", 18 },
};
static const EsheepTransition anim17_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim17_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim18_frames[] = { 8, 7, 6 };
static const EsheepTransition anim18_seq_next[] = {
    { 100, NULL, 7 },
};
static const EsheepTransition anim18_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim18_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim19_frames[] = { 3, 9, 10, 34, 35, 34, 35, 36, 36 };
static const EsheepTransition anim19_seq_next[] = {
    { 100, "none", 20 },
};
static const EsheepTransition anim19_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim19_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim20_frames[] = { 35, 36, 36, 35, 34, 34, 34, 10, 9 };
static const EsheepTransition anim20_seq_next[] = {
    { 100, "none", 1 },
};
static const EsheepTransition anim20_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim20_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim21_frames[] = { 134 };
static const EsheepTransition anim21_seq_next[] = {
    { 100, "none", 22 },
};
static const EsheepTransition anim21_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim21_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim22_frames[] = { 135, 135, 135, 135, 136, 136, 136, 136, 137, 137, 137, 137, 138, 138, 138, 138, 139, 139, 139, 139, 140, 140, 140, 140, 141, 141, 141, 141, 142, 142, 142, 142, 143, 143, 143, 143, 144, 144, 144, 144, 145, 144, 145, 144, 145, 144, 145, 144, 174, 174, 174, 174, 174, 174, 174 };
static const EsheepTransition anim22_seq_next[] = {
    { 100, "none", 47 },
};
static const EsheepTransition anim22_border_next[] = {
    { 100, "none", 47 },
};
static const EsheepTransition anim22_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim23_frames[] = { 146 };
static const EsheepTransition anim23_seq_next[] = {
    { 100, "none", 24 },
};
static const EsheepTransition anim23_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim23_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim24_frames[] = { 146, 146, 146, 146, 146, 146, 146, 146, 146, 146, 146, 146, 147, 147, 148, 148, 148, 147, 147, 146, 146, 146, 146, 146 };
static const EsheepTransition anim24_seq_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim24_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim24_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim25_frames[] = { 76, 30, 30, 30, 30, 23, 23, 23, 23, 23, 24, 24, 24, 24, 77 };
static const EsheepTransition anim25_seq_next[] = {
    { 100, "none", 7 },
};
static const EsheepTransition anim25_border_next[] = {
    { 80, "taskbar", 7 },
    { 20, "horizontal+", 36 },
};
static const EsheepTransition anim25_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim26_frames[] = { 6, 6, 6, 6, 58, 59, 59, 60, 61, 60, 61, 6 };
static const EsheepTransition anim26_seq_next[] = {
    { 100, "none", 1 },
};
static const EsheepTransition anim26_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim26_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim27_frames[] = { 174, 153, 153, 153, 153, 153, 149, 149, 149, 149, 149, 149, 149, 149, 149, 150, 150, 150, 150, 150, 150, 150, 151, 151, 151, 151, 151, 151, 151, 152, 152, 152, 152, 152, 152, 152, 174, 174, 174 };
static const EsheepTransition anim27_seq_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim27_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim27_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim28_frames[] = { 5, 4, 4 };
static const EsheepTransition anim28_seq_next[] = {
    { 100, "none", 29 },
};
static const EsheepTransition anim28_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim28_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim29_frames[] = { 2, 3 };
static const EsheepTransition anim29_seq_next[] = {
    { 100, "none", 30 },
};
static const EsheepTransition anim29_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim29_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim30_frames[] = { 8, 3, 3, 3, 127, 128, 129, 130, 130, 130, 130, 129, 128, 127, 3, 3, 3 };
static const EsheepTransition anim30_seq_next[] = {
    { 100, "none", 1 },
};
static const EsheepTransition anim30_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim30_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim31_frames[] = { 155, 154, 154 };
static const EsheepTransition anim31_seq_next[] = {
    { 100, "none", 32 },
};
static const EsheepTransition anim31_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim31_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim32_frames[] = { 156, 157 };
static const EsheepTransition anim32_seq_next[] = {
    { 100, "none", 33 },
};
static const EsheepTransition anim32_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim32_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim33_frames[] = { 157 };
static const EsheepTransition anim33_seq_next[] = {
    { 100, "none", 34 },
};
static const EsheepTransition anim33_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim33_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim34_frames[] = { 157 };
static const EsheepTransition anim34_seq_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim34_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim34_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim35_frames[] = { 2, 3, 2, 5, 4, 5, 4, 5 };
static const EsheepTransition anim35_seq_next[] = {
    { 100, "none", 7 },
};
static const EsheepTransition anim35_border_next[] = {
    { 100, "vertical", 8 },
};
static const EsheepTransition anim35_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim36_frames[] = { 5, 4, 5, 4, 5, 3, 2, 3, 2, 3 };
static const EsheepTransition anim36_seq_next[] = {
    { 100, "none", 1 },
};
static const EsheepTransition anim36_border_next[] = {
    { 100, "vertical", 8 },
};
static const EsheepTransition anim36_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim37_frames[] = { 31, 30, 15, 16 };
static const EsheepTransition anim37_seq_next[] = {
    { 100, "none", 37 },
};
static const EsheepTransition anim37_border_next[] = {
    { 100, "none", 38 },
};
static const EsheepTransition anim37_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim38_frames[] = { 16, 17, 28 };
static const EsheepTransition anim38_seq_next[] = {
    { 100, "none", 39 },
};
static const EsheepTransition anim38_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim38_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim39_frames[] = { 98, 97 };
static const EsheepTransition anim39_seq_next[] = {
    { 100, "none", 39 },
};
static const EsheepTransition anim39_border_next[] = {
    { 100, "none", 40 },
};
static const EsheepTransition anim39_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim40_frames[] = { 97, 97 };
static const EsheepTransition anim40_seq_next[] = {
    { 100, "none", 41 },
};
static const EsheepTransition anim40_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim40_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim41_frames[] = { 19, 20 };
static const EsheepTransition anim41_seq_next[] = {
    { 100, "none", 41 },
};
static const EsheepTransition anim41_border_next[] = {
    { 100, "none", 42 },
};
static const EsheepTransition anim41_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim42_frames[] = { 24, 6, 6, 6, 6, 6 };
static const EsheepTransition anim42_seq_next[] = {
    { 100, "none", 1 },
};
static const EsheepTransition anim42_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim42_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim43_frames[] = { 6, 78, 78, 78, 79, 80, 79, 78, 78, 78, 78, 78 };
static const EsheepTransition anim43_seq_next[] = {
    { 50, "none", 2 },
    { 40, "none", 44 },
    { 40, "none", 51 },
};
static const EsheepTransition anim43_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim43_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim44_frames[] = { 31, 30, 30, 4, 4, 4, 21, 25 };
static const EsheepTransition anim44_seq_next[] = {
    { 100, "none", 45 },
};
static const EsheepTransition anim44_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim44_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim45_frames[] = { 25, 25 };
static const EsheepTransition anim45_seq_next[] = {
    { 100, "none", 45 },
};
static const EsheepTransition anim45_border_next[] = {
    { 100, "none", 46 },
};
static const EsheepTransition anim45_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim46_frames[] = { 24, 23, 23, 23, 23, 23, 31, 3, 3, 3, 3 };
static const EsheepTransition anim46_seq_next[] = {
    { 100, "none", 1 },
};
static const EsheepTransition anim46_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim46_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim47_frames[] = { 169, 169, 169, 170, 171, 170, 169, 169 };
static const EsheepTransition anim47_seq_next[] = {
    { 100, "none", 48 },
};
static const EsheepTransition anim47_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim47_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim48_frames[] = { 119, 81, 81, 82, 82, 10 };
static const EsheepTransition anim48_seq_next[] = {
    { 100, "none", 3 },
};
static const EsheepTransition anim48_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim48_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim49_frames[] = { 2, 3 };
static const EsheepTransition anim49_seq_next[] = {
    { 10, "none", 19 },
    { 3, "none", 17 },
    { 80, "none", 1 },
};
static const EsheepTransition anim49_border_next[] = {
    { 100, "none", 2 },
    { 2, "vertical", 37 },
    { 20, "window", 43 },
};
static const EsheepTransition anim49_gravity_next[] = {
    { 100, "none", 5 },
};

static const int anim50_frames[] = { 2, 3 };
static const EsheepTransition anim50_seq_next[] = {
    { 10, "none", 19 },
    { 3, "none", 17 },
    { 80, "none", 1 },
};
static const EsheepTransition anim50_border_next[] = {
    { 100, "none", 2 },
    { 2, "vertical", 37 },
    { 20, "window", 43 },
};
static const EsheepTransition anim50_gravity_next[] = {
    { 100, "none", 1 },
};

static const int anim51_frames[] = { 77 };
static const EsheepTransition anim51_seq_next[] = {
    { 100, "none", 52 },
};
static const EsheepTransition anim51_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim51_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim52_frames[] = { 40, 41 };
static const EsheepTransition anim52_seq_next[] = {
    { 100, "none", 53 },
};
static const EsheepTransition anim52_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim52_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim53_frames[] = { 29, 29 };
static const EsheepTransition anim53_seq_next[] = {
    { 100, "none", 53 },
};
static const EsheepTransition anim53_border_next[] = {
    { 100, "none", 54 },
};
static const EsheepTransition anim53_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

static const int anim54_frames[] = { 45, 45, 18, 76, 6 };
static const EsheepTransition anim54_seq_next[] = {
    { 100, "none", 1 },
};
static const EsheepTransition anim54_border_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};
static const EsheepTransition anim54_gravity_next[] = {
    { 0, NULL, 0 }, /* unused placeholder, count is 0 */
};

const EsheepAnimation esheep_default_animations[] = {
    {
        1, "walk",
        { "-2", "0", 200, "0", 1.0 },
        { "-2", "0", 200, "0", 1.0 },
        "20", "0",
        anim1_frames, 2,
        0,
        anim1_seq_next, 6,
        anim1_border_next, 3,
        anim1_gravity_next, 1,
    },
    {
        2, "rotate1a",
        { "0", "0", 200, "0", 1.0 },
        { "0", "0", 200, "0", 1.0 },
        "0", "0",
        anim2_frames, 3,
        1,
        anim2_seq_next, 1,
        anim2_border_next, 0,
        anim2_gravity_next, 0,
    },
    {
        3, "rotate1b",
        { "0", "0", 200, "0", 1.0 },
        { "0", "0", 200, "0", 1.0 },
        "0", "0",
        anim3_frames, 3,
        0,
        anim3_seq_next, 2,
        anim3_border_next, 0,
        anim3_gravity_next, 0,
    },
    {
        4, "drag",
        { "0", "0", 100, "0", 1.0 },
        { "0", "0", 100, "0", 1.0 },
        "0", "0",
        anim4_frames, 6,
        0,
        anim4_seq_next, 1,
        anim4_border_next, 0,
        anim4_gravity_next, 0,
    },
    {
        5, "fall",
        { "0", "1", 100, "0", 1.0 },
        { "0", "10", 40, "0", 1.0 },
        "20", "0",
        anim5_frames, 1,
        0,
        anim5_seq_next, 1,
        anim5_border_next, 1,
        anim5_gravity_next, 0,
    },
    {
        6, "fall fast",
        { "0", "10", 40, "0", 1.0 },
        { "0", "10", 40, "2", 1.0 },
        "10", "0",
        anim6_frames, 3,
        0,
        anim6_seq_next, 1,
        anim6_border_next, 1,
        anim6_gravity_next, 0,
    },
    {
        7, "run",
        { "-10", "0", 100, "0", 1.0 },
        { "-10", "0", 100, "0", 1.0 },
        "5", "0",
        anim7_frames, 3,
        0,
        anim7_seq_next, 3,
        anim7_border_next, 1,
        anim7_gravity_next, 1,
    },
    {
        8, "boing",
        { "1", "0", 100, "0", 1.0 },
        { "10", "0", 100, "0", 1.0 },
        "0", "0",
        anim8_frames, 11,
        0,
        anim8_seq_next, 3,
        anim8_border_next, 0,
        anim8_gravity_next, 0,
    },
    {
        9, "fall soft",
        { "0", "0", 800, "1", 1.0 },
        { "0", "0", 200, "0", 1.0 },
        "0", "0",
        anim9_frames, 8,
        0,
        anim9_seq_next, 1,
        anim9_border_next, 0,
        anim9_gravity_next, 0,
    },
    {
        10, "fall hard",
        { "0", "0", 200, "2", 1.0 },
        { "0", "0", 500, "2", 1.0 },
        "0", "0",
        anim10_frames, 5,
        0,
        anim10_seq_next, 1,
        anim10_border_next, 0,
        anim10_gravity_next, 0,
    },
    {
        11, "pissa",
        { "0", "0", 200, "0", 1.0 },
        { "0", "0", 200, "0", 1.0 },
        "5+random/10", "5",
        anim11_frames, 7,
        0,
        anim11_seq_next, 1,
        anim11_border_next, 0,
        anim11_gravity_next, 0,
    },
    {
        12, "pissb",
        { "0", "0", 200, "0", 1.0 },
        { "0", "0", 200, "0", 1.0 },
        "0", "0",
        anim12_frames, 7,
        0,
        anim12_seq_next, 1,
        anim12_border_next, 0,
        anim12_gravity_next, 0,
    },
    {
        13, "kill",
        { "0", "0", 100, "0", 1.0 },
        { "0", "0", 200, "0", 1.0 },
        "20", "1",
        anim13_frames, 3,
        0,
        anim13_seq_next, 1,
        anim13_border_next, 0,
        anim13_gravity_next, 0,
    },
    {
        14, "sync",
        { "0", "0", 30, "0", 1.0 },
        { "0", "0", 100, "0", 1.0 },
        "12", "0",
        anim14_frames, 2,
        0,
        anim14_seq_next, 1,
        anim14_border_next, 0,
        anim14_gravity_next, 0,
    },
    {
        15, "sleep1a",
        { "0", "0", 1000, "0", 1.0 },
        { "0", "0", 200, "0", 1.0 },
        "random/5+10", "9",
        anim15_frames, 11,
        0,
        anim15_seq_next, 1,
        anim15_border_next, 0,
        anim15_gravity_next, 0,
    },
    {
        16, "sleep1b",
        { "0", "0", 200, "0", 1.0 },
        { "0", "0", 200, "0", 1.0 },
        "0", "0",
        anim16_frames, 11,
        0,
        anim16_seq_next, 1,
        anim16_border_next, 0,
        anim16_gravity_next, 0,
    },
    {
        17, "sleep2a",
        { "0", "0", 200, "0", 1.0 },
        { "0", "0", 200, "0", 1.0 },
        "random/10+20", "6",
        anim17_frames, 8,
        0,
        anim17_seq_next, 1,
        anim17_border_next, 0,
        anim17_gravity_next, 0,
    },
    {
        18, "sleep2b",
        { "0", "0", 200, "0", 1.0 },
        { "0", "0", 200, "0", 1.0 },
        "0", "0",
        anim18_frames, 3,
        0,
        anim18_seq_next, 1,
        anim18_border_next, 0,
        anim18_gravity_next, 0,
    },
    {
        19, "sleep3a",
        { "0", "0", 200, "1", 1.0 },
        { "0", "0", 200, "1", 1.0 },
        "random/10+30", "7",
        anim19_frames, 9,
        0,
        anim19_seq_next, 1,
        anim19_border_next, 0,
        anim19_gravity_next, 0,
    },
    {
        20, "sleep3b",
        { "0", "0", 200, "1", 1.0 },
        { "0", "0", 200, "0", 1.0 },
        "0", "0",
        anim20_frames, 9,
        0,
        anim20_seq_next, 1,
        anim20_border_next, 0,
        anim20_gravity_next, 0,
    },
    {
        21, "batha",
        { "-2", "2", 30, "0", 1.0 },
        { "-2", "2", 30, "0", 1.0 },
        "(areaH/2+(randS*areaH/2)/120-imageH-68)/2", "0",
        anim21_frames, 1,
        0,
        anim21_seq_next, 1,
        anim21_border_next, 0,
        anim21_gravity_next, 0,
    },
    {
        22, "bathb",
        { "-2", "2", 30, "0", 1.0 },
        { "-2", "2", 32, "0", 1.0 },
        "0", "0",
        anim22_frames, 55,
        0,
        anim22_seq_next, 1,
        anim22_border_next, 1,
        anim22_gravity_next, 0,
    },
    {
        23, "bathw",
        { "0", "0", 30, "0", 1.0 },
        { "0", "0", 30, "0", 1.0 },
        "(areaH/2+(randS*areaH/2)/120-imageH-10)/2", "0",
        anim23_frames, 1,
        0,
        anim23_seq_next, 1,
        anim23_border_next, 0,
        anim23_gravity_next, 0,
    },
    {
        24, "bathz",
        { "0", "0", 30, "0", 1.0 },
        { "0", "0", 50, "0", 1.0 },
        "5", "20",
        anim24_frames, 24,
        0,
        anim24_seq_next, 0,
        anim24_border_next, 0,
        anim24_gravity_next, 0,
    },
    {
        25, "jump",
        { "-10", "-15", 100, "0", 1.0 },
        { "-10", "15", 100, "0", 1.0 },
        "0", "0",
        anim25_frames, 15,
        0,
        anim25_seq_next, 1,
        anim25_border_next, 2,
        anim25_gravity_next, 0,
    },
    {
        26, "eat",
        { "0", "0", 300, "0", 1.0 },
        { "0", "0", 300, "0", 1.0 },
        "5", "5",
        anim26_frames, 12,
        0,
        anim26_seq_next, 1,
        anim26_border_next, 0,
        anim26_gravity_next, 0,
    },
    {
        27, "flower",
        { "0", "0", 300, "0", 0.8 },
        { "0", "0", 300, "0", 1.0 },
        "0", "0",
        anim27_frames, 39,
        0,
        anim27_seq_next, 0,
        anim27_border_next, 0,
        anim27_gravity_next, 0,
    },
    {
        28, "blacksheepa",
        { "-10", "0", 100, "0", 1.0 },
        { "-10", "0", 100, "0", 1.0 },
        "(screenW/2)/30-6", "0",
        anim28_frames, 3,
        0,
        anim28_seq_next, 1,
        anim28_border_next, 0,
        anim28_gravity_next, 0,
    },
    {
        29, "blacksheepb",
        { "-6", "0", 100, "0", 1.0 },
        { "0", "0", 100, "0", 1.0 },
        "25+(Convert(screenW/2,System.Int32)%30)/7", "0",
        anim29_frames, 2,
        0,
        anim29_seq_next, 1,
        anim29_border_next, 0,
        anim29_gravity_next, 0,
    },
    {
        30, "blacksheepc",
        { "0", "0", 500, "0", 1.0 },
        { "0", "0", 500, "0", 1.0 },
        "0", "0",
        anim30_frames, 17,
        0,
        anim30_seq_next, 1,
        anim30_border_next, 0,
        anim30_gravity_next, 0,
    },
    {
        31, "blacksheepv",
        { "10", "0", 100, "0", 1.0 },
        { "10", "0", 100, "0", 1.0 },
        "(screenW/2)/30-6", "0",
        anim31_frames, 3,
        0,
        anim31_seq_next, 1,
        anim31_border_next, 0,
        anim31_gravity_next, 0,
    },
    {
        32, "blacksheepw",
        { "6", "0", 100, "0", 1.0 },
        { "0", "0", 100, "0", 1.0 },
        "24+(Convert(screenW/2,System.Int32)%30)/7", "0",
        anim32_frames, 2,
        0,
        anim32_seq_next, 1,
        anim32_border_next, 0,
        anim32_gravity_next, 0,
    },
    {
        33, "blacksheepy",
        { "0", "0", 500, "0", 1.0 },
        { "0", "0", 500, "0", 1.0 },
        "9", "0",
        anim33_frames, 1,
        0,
        anim33_seq_next, 1,
        anim33_border_next, 0,
        anim33_gravity_next, 0,
    },
    {
        34, "blacksheepz",
        { "0", "0", 20, "0", 1.0 },
        { "0", "0", 20, "0", 0.0 },
        "20", "0",
        anim34_frames, 1,
        0,
        anim34_seq_next, 0,
        anim34_border_next, 0,
        anim34_gravity_next, 0,
    },
    {
        35, "run_begin",
        { "-2", "0", 200, "0", 1.0 },
        { "-10", "0", 100, "0", 1.0 },
        "0", "0",
        anim35_frames, 8,
        0,
        anim35_seq_next, 1,
        anim35_border_next, 1,
        anim35_gravity_next, 0,
    },
    {
        36, "run_end",
        { "-10", "0", 100, "0", 1.0 },
        { "-2", "0", 200, "0", 1.0 },
        "0", "0",
        anim36_frames, 10,
        0,
        anim36_seq_next, 1,
        anim36_border_next, 1,
        anim36_gravity_next, 0,
    },
    {
        37, "vertical_walk_up",
        { "0", "-2", 150, "0", 1.0 },
        { "0", "-2", 150, "0", 1.0 },
        "5000", "2",
        anim37_frames, 4,
        0,
        anim37_seq_next, 1,
        anim37_border_next, 1,
        anim37_gravity_next, 0,
    },
    {
        38, "top_walk",
        { "0", "0", 200, "0", 1.0 },
        { "2", "0", 200, "0", 1.0 },
        "0", "0",
        anim38_frames, 3,
        1,
        anim38_seq_next, 1,
        anim38_border_next, 0,
        anim38_gravity_next, 0,
    },
    {
        39, "top_walk2",
        { "-2", "0", 150, "-2", 1.0 },
        { "-2", "0", 150, "-2", 1.0 },
        "5000", "0",
        anim39_frames, 2,
        0,
        anim39_seq_next, 1,
        anim39_border_next, 1,
        anim39_gravity_next, 0,
    },
    {
        40, "top_walk3",
        { "0", "0", 800, "0", 1.0 },
        { "0", "0", 800, "0", 1.0 },
        "0", "0",
        anim40_frames, 2,
        1,
        anim40_seq_next, 1,
        anim40_border_next, 0,
        anim40_gravity_next, 0,
    },
    {
        41, "vertical_walk_down",
        { "0", "2", 150, "0", 1.0 },
        { "0", "2", 150, "0", 1.0 },
        "5000", "0",
        anim41_frames, 2,
        0,
        anim41_seq_next, 1,
        anim41_border_next, 1,
        anim41_gravity_next, 0,
    },
    {
        42, "vertical_walk_over",
        { "0", "0", 200, "0", 1.0 },
        { "0", "0", 200, "0", 1.0 },
        "0", "0",
        anim42_frames, 6,
        0,
        anim42_seq_next, 1,
        anim42_border_next, 0,
        anim42_gravity_next, 0,
    },
    {
        43, "look_down",
        { "0", "0", 120, "0", 1.0 },
        { "0", "0", 120, "0", 1.0 },
        "0", "0",
        anim43_frames, 12,
        0,
        anim43_seq_next, 3,
        anim43_border_next, 0,
        anim43_gravity_next, 0,
    },
    {
        44, "jump_down",
        { "-5", "-10", 150, "0", 1.0 },
        { "-20", "10", 150, "0", 1.0 },
        "0", "0",
        anim44_frames, 8,
        0,
        anim44_seq_next, 1,
        anim44_border_next, 0,
        anim44_gravity_next, 0,
    },
    {
        45, "jump_down2",
        { "0", "10", 50, "0", 1.0 },
        { "0", "10", 50, "0", 1.0 },
        "100", "0",
        anim45_frames, 2,
        0,
        anim45_seq_next, 1,
        anim45_border_next, 1,
        anim45_gravity_next, 0,
    },
    {
        46, "jump_down3",
        { "0", "0", 50, "0", 1.0 },
        { "0", "0", 200, "0", 1.0 },
        "0", "0",
        anim46_frames, 11,
        0,
        anim46_seq_next, 1,
        anim46_border_next, 0,
        anim46_gravity_next, 0,
    },
    {
        47, "bathc",
        { "0", "0", 100, "0", 1.0 },
        { "0", "0", 100, "0", 1.0 },
        "0", "0",
        anim47_frames, 8,
        0,
        anim47_seq_next, 1,
        anim47_border_next, 0,
        anim47_gravity_next, 0,
    },
    {
        48, "bathd",
        { "0", "0", 100, "-20", 1.0 },
        { "0", "0", 100, "0", 1.0 },
        "0", "0",
        anim48_frames, 6,
        0,
        anim48_seq_next, 1,
        anim48_border_next, 0,
        anim48_gravity_next, 0,
    },
    {
        49, "walk_win2",
        { "-2", "0", 200, "0", 1.0 },
        { "-2", "0", 200, "0", 1.0 },
        "10", "0",
        anim49_frames, 2,
        0,
        anim49_seq_next, 3,
        anim49_border_next, 3,
        anim49_gravity_next, 1,
    },
    {
        50, "walk_task2",
        { "-2", "0", 200, "0", 1.0 },
        { "-2", "0", 200, "0", 1.0 },
        "10", "0",
        anim50_frames, 2,
        0,
        anim50_seq_next, 3,
        anim50_border_next, 3,
        anim50_gravity_next, 1,
    },
    {
        51, "fall_wina",
        { "-imageW*0.7", "imageH*0.45", 100, "0", 1.0 },
        { "0", "0", 100, "0", 1.0 },
        "0", "0",
        anim51_frames, 1,
        1,
        anim51_seq_next, 1,
        anim51_border_next, 0,
        anim51_gravity_next, 0,
    },
    {
        52, "fall_winb",
        { "0", "0", 100, "0", 1.0 },
        { "0", "1", 100, "0", 1.0 },
        "10+random/10", "0",
        anim52_frames, 2,
        0,
        anim52_seq_next, 1,
        anim52_border_next, 0,
        anim52_gravity_next, 0,
    },
    {
        53, "fall_winc",
        { "0", "4", 50, "0", 1.0 },
        { "0", "20", 50, "0", 1.0 },
        "300", "0",
        anim53_frames, 2,
        0,
        anim53_seq_next, 1,
        anim53_border_next, 1,
        anim53_gravity_next, 0,
    },
    {
        54, "fall_wind",
        { "0", "0", 500, "0", 1.0 },
        { "0", "0", 500, "0", 1.0 },
        "0", "0",
        anim54_frames, 5,
        0,
        anim54_seq_next, 1,
        anim54_border_next, 0,
        anim54_gravity_next, 0,
    },
};
const int esheep_default_animation_count = 54;

const EsheepChild esheep_default_childs[] = {
    {
        21, "screenW+10-areaH/2-(randS*areaH/2)/120", "areaH-imageH", 23
    },
    {
        26, "imageX-imageW*0.9", "imageY", 27
    },
    {
        28, "-imageW-8", "imageY", 31
    },
};
const int esheep_default_child_count = 3;

int esheep_tiles_x = esheep_default_tiles_x;
int esheep_tiles_y = esheep_default_tiles_y;
const EsheepSpawn *esheep_spawns = esheep_default_spawns;
int esheep_spawn_count = esheep_default_spawn_count;
const EsheepAnimation *esheep_animations = esheep_default_animations;
int esheep_animation_count = esheep_default_animation_count;
const EsheepChild *esheep_childs = esheep_default_childs;
int esheep_child_count = esheep_default_child_count;

void esheep_use_default_animation_data(void) {
    esheep_tiles_x = esheep_default_tiles_x;
    esheep_tiles_y = esheep_default_tiles_y;
    esheep_spawns = esheep_default_spawns;
    esheep_spawn_count = esheep_default_spawn_count;
    esheep_animations = esheep_default_animations;
    esheep_animation_count = esheep_default_animation_count;
    esheep_childs = esheep_default_childs;
    esheep_child_count = esheep_default_child_count;
}
